title: LoTide 
logo: /assets/img/logo.png
description: A system for creating dynamic music.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/LoTide
