title: LoTide 
description: A system for creating dynamic music.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/LoTide
  is_project_page: true
